# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('mood_chk', models.IntegerField(choices=[(1, 'VeryBad'), (2, 'Bad'), (3, 'Good'), (4, 'VeryGood')])),
                ('mood_comment', models.CharField(max_length=400)),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
    ]
