# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('mood_chk', models.CharField(choices=[('Bad', '1'), ('SoSo', '2'), ('Good', '3'), ('VaryGood', '4')], default='friendly', max_length=100)),
                ('mood_comment', models.CharField(max_length=400)),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
        migrations.CreateModel(
            name='MoodQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mood',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.MoodQuestion'),
        ),
    ]
