# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood_chk',
            field=models.CharField(choices=[('Bad', '1'), ('SoSo', '2'), ('Good', '3'), ('VaryGood', '4')], max_length=100),
        ),
    ]
